---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchlist
  template:
    metadata:
      labels:
        app: watchlist
    spec:
      containers:
        - name: watchlist-api
          image: docker.io/ekelhala/pwp-api-server:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: watchlist-secrets
                  key: MONGODB_CONNECTION_STRING
        - name: watchlist-client
          image: docker.io/ekelhala/pwp-client:latest
          ports:
            - containerPort: 3000
              protocol: TCP
        - name: reverse-proxy
          image: docker.io/ekelhala/pwp-nginx-proxy
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: watchlist-entrypoint
spec:
  type: NodePort
  selector:
    app: watchlist
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
